export const CHANGE_DIRECTORY = 'CHANGE_DIRECTORY'
export const FETCH_DIRECTORY_CONTENT_STARTED = 'FETCH_DIRECTORY_CONTENT'
export const FETCH_DIRECTORY_CONTENT_SUCCEEDED = 'FETCH_DIRECTORY_CONTENT_SUCCEEDED'
export const FETCH_DIRECTORY_CONTENT_FAILED = 'FETCH_DIRECTORY_CONTENT_FAILED'
