export const LS = 'ls';
export const CD = 'cd';
export const HELP = 'help';
export const HISTORY = 'history';
export const CLEAR = 'clear';
export const CAT = 'cat';
export const LS_HELP = ' ls: List all files and folders in this directory'
export const CD_HELP = [' cd:', ' cd: Change directory to ROOT','cd .. : Move up one level from the current directory','cd [FOLDER]: Change directory to this folder']
export const HISTORY_HELP = ' history: List all commands used'
export const CLEAR_HELP = ' clear: Clear terminal from all commands'
export const CAT_HELP = 'cat [FILE]: print the content of the file'
export const NOT_FOUND = 'command not found'
export const DIR_NOT_FOUND = 'No such directory'
